### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by nixsiow** [bachya/lp-vault-manager#12]
Failed to login. Nothing happen once I press login, no place for password to enter. And show error when I choose 'login to lastpass'. (Error in workflow:<path> Error2: no such file or directory)

lpass cli installed, logined and working great.

I have multifactor action enabled(yubikey or google authentication), not sure this will cause any problem. Do you cover this part? Cheers.

![screen shot 2015-03-12 at 1 18 05 pm 1](https://cloud.githubusercontent.com/assets/4393626/6612611/84596a44-c8ba-11e4-80c6-d57324c361ae.jpg)

**Comment by lfender6445** [comment]
:+1: same issue here - in my case the issue was a missing `workflow.py` file - but if I check debug in alfred preferences and copy the path, it exists

**Comment by lfender6445** [comment]
full debug output 

```
[STDERR: alfred.workflow.input.scriptfilter] 18:44:48 workflow.py:1386 DEBUG    Reading settings from `/Users/lfender_mbp/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
18:44:48 workflow.py:1960 DEBUG    Workflow version : 4.2.0
18:44:48 workflow.py:2221 DEBUG    Update check not due
18:44:48 lpsettings_query.py:35 DEBUG    Query arguments: [u'']
18:44:48 lpsettings_query.py:43 DEBUG    Parsed command: list-settings
18:44:48 lpsettings_query.py:44 DEBUG    Parsed argument: None
18:44:48 lpsettings_query.py:45 DEBUG    Parsed delimiter: >
18:44:48 lpsettings_query.py:46 DEBUG    Parsed query: list-settings
18:44:48 workflow.py:1996 DEBUG    Workflow finished in 0.017 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 18:44:50 workflow.py:1386 DEBUG    Reading settings from `/Users/lfender_mbp/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
18:44:50 workflow.py:1960 DEBUG    Workflow version : 4.2.0
18:44:50 workflow.py:2221 DEBUG    Update check not due
18:44:50 lpsettings_query.py:35 DEBUG    Query arguments: [u'check-for-update']
18:44:50 lpsettings_query.py:43 DEBUG    Parsed command: check-for-update
18:44:50 lpsettings_query.py:44 DEBUG    Parsed argument: None
18:44:50 lpsettings_query.py:45 DEBUG    Parsed delimiter: >
18:44:50 lpsettings_query.py:46 DEBUG    Parsed query: check-for-update
18:44:50 workflow.py:1609 DEBUG    Loading cached data from : /Users/lfender_mbp/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.bachya.lpvm/__workflow_update_status.cpickle
18:44:50 workflow.py:2169 DEBUG    update_data : {u'available': False}
18:44:50 workflow.py:1996 DEBUG    Workflow finished in 0.015 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 18:44:53 workflow.py:1386 DEBUG    Reading settings from `/Users/lfender_mbp/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
18:44:53 workflow.py:1960 DEBUG    Workflow version : 4.2.0
18:44:53 workflow.py:2221 DEBUG    Update check not due
18:44:53 lpsettings_query.py:35 DEBUG    Query arguments: [u'']
18:44:53 lpsettings_query.py:43 DEBUG    Parsed command: list-settings
18:44:53 lpsettings_query.py:44 DEBUG    Parsed argument: None
18:44:53 lpsettings_query.py:45 DEBUG    Parsed delimiter: >
18:44:53 lpsettings_query.py:46 DEBUG    Parsed query: list-settings
18:44:53 workflow.py:1996 DEBUG    Workflow finished in 0.014 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 18:44:55 workflow.py:1386 DEBUG    Reading settings from `/Users/lfender_mbp/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
18:44:55 workflow.py:1960 DEBUG    Workflow version : 4.2.0
18:44:55 workflow.py:2221 DEBUG    Update check not due
18:44:55 lpsettings_query.py:35 DEBUG    Query arguments: [u'list-lp-settings']
18:44:55 lpsettings_query.py:43 DEBUG    Parsed command: list-lp-settings
18:44:55 lpsettings_query.py:44 DEBUG    Parsed argument: None
18:44:55 lpsettings_query.py:45 DEBUG    Parsed delimiter: >
18:44:55 lpsettings_query.py:46 DEBUG    Parsed query: list-lp-settings
18:44:55 workflow.py:1996 DEBUG    Workflow finished in 0.018 seconds.
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 18:44:57 workflow.py:1386 DEBUG    Reading settings from `/Users/lfender_mbp/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
18:44:57 workflow.py:1960 DEBUG    Workflow version : 4.2.0
18:44:57 workflow.py:2221 DEBUG    Update check not due
18:44:57 lpsettings_query.py:35 DEBUG    Query arguments: [u'lastpass-login']
18:44:57 lpsettings_query.py:43 DEBUG    Parsed command: lastpass-login
18:44:57 lpsettings_query.py:44 DEBUG    Parsed argument: None
18:44:57 lpsettings_query.py:45 DEBUG    Parsed delimiter: >
18:44:57 lpsettings_query.py:46 DEBUG    Parsed query: lastpass-login
18:44:57 lpsettings_query.py:71 DEBUG    Executing command: lastpass-login
18:44:57 workflow.py:1978 ERROR    [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/lfender_mbp/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.B6B90E3B-BD2C-4EBA-B286-352DAD30639F/workflow/workflow.py", line 1971, in run
    func(self)
  File "lpsettings_query.py", line 72, in main
    if util.is_logged_in():
  File "/Users/lfender_mbp/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.B6B90E3B-BD2C-4EBA-B286-352DAD30639F/utilities.py", line 148, in is_logged_in
    [self.wf.settings['lastpass']['path'], 'ls']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
18:44:57 workflow.py:1996 DEBUG    Workflow finished in 0.021 seconds.
```

**Comment by lfender6445** [comment]
just a guess but perhaps it can't find the file because spaces aren't escaped?

**Comment by magnotti** [comment]
Same issue here.  Any fix?

![error](https://cloud.githubusercontent.com/assets/13136469/8456499/73ecac80-203e-11e5-9e77-2229465b3ab5.jpg)

**Comment by dennisSmidswater** [comment]
Same here, can't seem to figure out whats wrong but /usr/local/bin/lpass does nog exist, any idea on how to manually create this file?

**Comment by mr-mcox** [comment]
@dennisSmidswater I had the same issue as you, but finally realized that I hadn't yet installed the lastpass command line interface according to these directions: https://github.com/bachya/lp-vault-manager#installing-lastpass-cli
